spring:
  application:
    name:  itoken-config

  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Naomei-0007/itoken-config.git
          search-paths: respon
          username: Naomei-0007
          password: 123gemengyuan

server:
  port: 8888


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
